#!/bin/bash
# CodeJudge Mobile App - Quick Commands Reference

echo "🚀 CodeJudge Mobile App - Development Commands"
echo "=============================================="
echo ""
echo "📦 Installation:"
echo "  npm install              - Install all dependencies"
echo ""
echo "🏃 Development:"
echo "  npm start                - Start development server"
echo "  npm run android          - Run on Android emulator"
echo "  npm run ios              - Run on iOS simulator"
echo "  npm run web              - Run in web browser"
echo ""
echo "🧹 Cleaning:"
echo "  npm expo prebuild --clean - Clean build files"
echo "  npm expo start -c         - Clear cache and start"
echo ""
echo "📱 Debugging:"
echo "  • Press 'd' in Expo CLI for DevTools"
echo "  • Press 'j' to open debugger"
echo "  • Press 'i' to open iOS simulator"
echo "  • Press 'a' to open Android emulator"
echo ""
echo "🔧 Configuration:"
echo "  Create .env.local with: EXPO_PUBLIC_API_URL=http://10.0.2.2:5000/api"
echo ""
echo "📚 Documentation:"
echo "  • README.md      - Feature overview"
echo "  • SETUP.md       - Quick start guide"
echo "  • ARCHITECTURE.md - Detailed architecture"
echo ""
echo "Backend must be running: cd ../backend && npm run dev"
