import { useState, useEffect } from 'react';
import api from '../../services/api';
import { useLocation } from 'react-router-dom';
import { Search, Shield, User, TrendingUp, BarChart3 } from 'lucide-react';

const CreateUserForm = ({ onCreated }) => {
  const [username, setUsername] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [fullName, setFullName] = useState('');
  const [role, setRole] = useState('user');
  const [className, setClassName] = useState('NONE');
  // studentId will be auto-generated by backend for students; do not accept manual input
  const [teacherClasses, setTeacherClasses] = useState('');
  const [loading, setLoading] = useState(false);

  const handleCreate = async (e) => {
    e.preventDefault();
    setLoading(true);
    try {
      const payload = { username, email, password, fullName, role };
      if (role === 'user') payload.class = className;
      if (role === 'user' && studentId) payload.studentId = studentId;
      if (role === 'teacher') payload.teacherClasses = teacherClasses.split(',').map(s=>s.trim()).filter(Boolean);

      await api.post('/users/admin/users', payload);
      setUsername(''); setEmail(''); setPassword(''); setFullName(''); setRole('user'); setClassName('NONE'); setTeacherClasses(''); setStudentId('');
      if (onCreated) onCreated();
      alert('Tạo người dùng thành công');
    } catch (err) {
      console.error('Create user', err);
      alert(err.response?.data?.error || 'Lỗi khi tạo người dùng');
    } finally {
      setLoading(false);
    }
  };

  return (
    <form onSubmit={handleCreate} className="grid grid-cols-1 md:grid-cols-12 gap-3 items-center" autoComplete="off">
      <input name="create-username" autoComplete="off" value={username} onChange={e => setUsername(e.target.value)} placeholder="Tên đăng nhập" className="col-span-12 md:col-span-3 p-2 border rounded-md text-sm" required />
      <input name="create-fullname" autoComplete="off" value={fullName} onChange={e => setFullName(e.target.value)} placeholder="Họ và tên" className="col-span-12 md:col-span-3 p-2 border rounded-md text-sm" />
      <input name="create-email" autoComplete="off" value={email} onChange={e => setEmail(e.target.value)} placeholder="Email" className="col-span-12 md:col-span-3 p-2 border rounded-md text-sm" type="email" required />
      <input name="create-password" autoComplete="new-password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Mật khẩu" className="col-span-12 md:col-span-3 p-2 border rounded-md text-sm" type="password" required />

      <label className="sr-only">Role</label>
      <select value={role} onChange={e => setRole(e.target.value)} className="col-span-12 md:col-span-2 p-2 border rounded-md text-sm">
        <option value="user">Học sinh</option>
        <option value="teacher">Giáo viên</option>
        <option value="admin">Quản trị</option>
      </select>

      <div className="col-span-12 md:col-span-8">
        {role === 'teacher' ? (
          <input value={teacherClasses} onChange={e => setTeacherClasses(e.target.value)} placeholder="Các lớp (ví dụ: 10A1,10A2)" className="w-full p-2 border rounded-md text-sm" />
        ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
            <input value={className} onChange={e => setClassName(e.target.value)} placeholder="Lớp (ví dụ: 10A1)" className="w-full p-2 border rounded-md text-sm" />
            <input value={"(auto)"} readOnly placeholder="Mã số sinh viên (tự động)" className="w-full p-2 border rounded-md text-sm bg-gray-50" />
          </div>
        )}
      </div>

      <div className="col-span-12 md:col-span-2 text-right">
        <button type="submit" disabled={loading} className="inline-flex items-center justify-center w-full bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 rounded-md text-sm">
          {loading ? 'Đang tạo...' : 'Tạo người dùng'}
        </button>
      </div>
    </form>
  );
};

const AdminUsers = () => {
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [classes, setClasses] = useState([]);
  const [assignModalOpen, setAssignModalOpen] = useState(false);
  const [selectedUser, setSelectedUser] = useState(null);
  const [selectedClass, setSelectedClass] = useState('');
  const [assigning, setAssigning] = useState(false);
  const location = useLocation();
  const params = new URLSearchParams(location.search);
  const initialRole = params.get('role') || 'all';
  const [roleFilter, setRoleFilter] = useState(initialRole);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [totalPagesState, setTotalPagesState] = useState(1);
  const [totalResults, setTotalResults] = useState(0);
  const [roleCountsState, setRoleCountsState] = useState({});

  useEffect(() => {
    fetchClasses();
  }, []);

  useEffect(() => {
    fetchUsers();
  }, [roleFilter, page, pageSize, search]);

  const fetchUsers = async () => {
    try {
      setLoading(true);
      const params = {
        page,
        limit: pageSize,
        role: roleFilter,
      };
      if (search) params.search = search;
      const response = await api.get('/users/leaderboard', { params });
      setUsers(response.data.leaderboard || []);
      setTotalPagesState(response.data.totalPages || 1);
      setTotalResults(response.data.total || 0);
      setRoleCountsState(response.data.roleCounts || {});
    } catch (error) {
      console.error('Error fetching users:', error);
    } finally {
      setLoading(false);
    }
  };

  const fetchClasses = async () => {
    try {
      const res = await api.get('/admin/classes');
      setClasses(res.data.classes || []);
    } catch (err) {
      console.error('Error fetching classes', err);
      setClasses([]);
    }
  };

  const roleCounts = roleCountsState;

  const openAssignModal = (user) => {
    setSelectedUser(user);
    setSelectedClass('');
    setAssignModalOpen(true);
  };

  const handleAssign = async (e) => {
    e.preventDefault();
    if (!selectedUser || !selectedClass) return;
    try {
      setAssigning(true);
      await api.post(`/admin/classes/${selectedClass}/students`, { userId: selectedUser._id });
      alert('Gán lớp thành công');
      setAssignModalOpen(false);
      fetchUsers();
      fetchClasses();
    } catch (err) {
      console.error('Assign error', err);
      alert(err.response?.data?.error || 'Không thể gán lớp');
    } finally {
      setAssigning(false);
    }
  };

  // Resolve a stored user.class (could be name, slug, or compacted) to a known class
  // Returns { name: string, found: boolean }
  const getClassDisplay = (userClass) => {
    if (!userClass) return { name: '---', found: true };
    const raw = String(userClass || '');
    const target = raw.toLowerCase();

    // Handle special reserved class values
    if (target === 'admin') return { name: 'ADMIN', found: true };
    if (target === 'teacher') return { name: 'TEACHER', found: true };
    if (target === 'none') return { name: 'NONE', found: true };

    const found = classes.find(c => {
      if (!c) return false;
      const name = String(c.name || '').toLowerCase();
      const slug = String((c.slug || c.name || '')).toLowerCase();
      const compact = name.replace(/\s+/g, '').toLowerCase();
      return target === name || target === slug || target === compact;
    });
    if (found) return { name: found.name, found: true };
    return { name: String(userClass), found: false };
  };

  // reset page when filter/search/pageSize changes
  useEffect(() => {
    setPage(1);
  }, [roleFilter, search, pageSize]);

  const paginatedUsers = users; // server already returns paginated page
  const totalPages = totalPagesState;

  if (loading) {
    return (
      <div className="flex justify-center items-center h-screen">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-purple-600"></div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-8xl mx-auto px-4 py-8">
        <div className="mb-8">
          <h1 className="text-4xl font-bold text-gray-800 mb-2">Manage Users</h1>
          <p className="text-gray-600">{users.length} registered users</p>
        </div>
        {/* Create user form */}
        <div className="bg-white rounded-xl shadow-md p-4 mb-6">
          <h3 className="font-semibold mb-3">Tạo người dùng mới</h3>
          <CreateUserForm onCreated={fetchUsers} />
        </div>

        {/* Search */}
        {/* Role filters */}
          <div className="flex items-center space-x-3 mb-4">
          <button onClick={() => setRoleFilter('admin')} className={`px-4 py-2 rounded-md ${roleFilter==='admin' ? 'bg-orange-600 text-white' : 'bg-white border'}`}>
            Admin ({roleCounts.admin || 0})
          </button>
          <button onClick={() => setRoleFilter('teacher')} className={`px-4 py-2 rounded-md ${roleFilter==='teacher' ? 'bg-purple-600 text-white' : 'bg-white border'}`}>
            Teacher ({roleCounts.teacher || 0})
          </button>
          <button onClick={() => setRoleFilter('user')} className={`px-4 py-2 rounded-md ${roleFilter==='user' ? 'bg-blue-600 text-white' : 'bg-white border'}`}>
            Students ({roleCounts.user || 0})
          </button>
        </div>

        {/* Search */}
        <div className="bg-white rounded-xl shadow-md p-4 mb-6">
          <div className="relative">
            <Search className="absolute left-3 top-3.5 text-gray-400" size={20} />
            <input
              type="text"
              placeholder="Search users..."
              className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>
        </div>

        {/* Users Table */}
        <div className="bg-white rounded-xl shadow-md overflow-x-auto">
          <table className="min-w-[1100px] w-full">
            <thead className="bg-gray-50 border-b">
              <tr>
                <th className="px-6 py-4 text-left text-sm font-semibold text-gray-600">Rank</th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-gray-600">User</th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-gray-600">Mã SV</th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-gray-600">Class</th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-gray-600">Email</th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-gray-600">Rating</th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-gray-600">Solved</th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-gray-600">Role</th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-gray-600 sticky right-0 bg-white">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-200">
              {paginatedUsers.map((user) => (
                <tr key={user._id} className="hover:bg-gray-50">
                  <td className="px-6 py-4 text-gray-600">
                    #{user.rank}
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center space-x-3">
                      <div className="w-10 h-10 bg-gradient-to-r from-indigo-600 to-purple-600 rounded-full flex items-center justify-center text-white font-bold">
                        {user.username[0].toUpperCase()}
                      </div>
                      <div>
                        <div className="font-semibold text-gray-800">{user.username}</div>
                        {user.fullName && (
                          <div className="text-sm text-gray-500">{user.fullName}</div>
                        )}
                      </div>
                    </div>
                  </td>
                  <td className="px-6 py-4 text-gray-600">
                    {user.studentId || '-'}
                  </td>
                  <td className="px-6 py-4 text-gray-600">
                    {(() => {
                      const resolved = getClassDisplay(user.class);
                      if (resolved.found) {
                        return resolved.name;
                      }
                      return (
                        <span className="text-sm text-red-600">
                          {resolved.name}
                          <span className="ml-2 text-xs text-gray-500">(Không tìm thấy lớp)</span>
                        </span>
                      );
                    })()}
                  </td>
                  <td className="px-6 py-4 text-gray-600">
                    {user.email || 'N/A'}
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center space-x-2">
                      <TrendingUp className="text-purple-600" size={16} />
                      <span className="font-semibold text-purple-600">{user.rating}</span>
                    </div>
                  </td>
                  <td className="px-6 py-4 text-gray-600">
                    {user.solvedProblems}
                  </td>
                  <td className="px-6 py-4">
                    <span className={`px-3 py-1 rounded-full text-xs font-semibold ${
                      user.role === 'admin' ? 'bg-orange-100 text-orange-800' :
                      user.role === 'teacher' ? 'bg-purple-100 text-purple-800' :
                      'bg-blue-100 text-blue-800'
                    }`}>
                      {user.role === 'admin' ? (
                        <span className="flex items-center space-x-1">
                          <Shield size={12} />
                          <span>ADMIN</span>
                        </span>
                      ) : user.role === 'teacher' ? (
                        <span className="flex items-center space-x-1">
                          <BarChart3 size={12} />
                          <span>TEACHER</span>
                        </span>
                      ) : (
                        <span className="flex items-center space-x-1">
                          <User size={12} />
                          <span>USER</span>
                        </span>
                      )}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-right min-w-[150px] sticky right-0 bg-white">
                    {user.role === 'user' ? (
                      <button onClick={() => openAssignModal(user)} className="px-3 py-1 bg-blue-600 text-white rounded-md text-sm">Gán lớp</button>
                    ) : (
                      <span className="text-sm text-gray-500">-</span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Pagination Controls */}
        <div className="flex items-center justify-between mt-4">
          <div className="flex items-center space-x-2">
            <button onClick={() => setPage(p => Math.max(1, p-1))} disabled={page===1} className="px-3 py-1 border rounded-md">Prev</button>
            <span className="text-sm">Trang {page} / {totalPages}</span>
            <button onClick={() => setPage(p => Math.min(totalPages, p+1))} disabled={page===totalPages} className="px-3 py-1 border rounded-md">Next</button>
          </div>

          <div className="flex items-center space-x-2">
            <label className="text-sm">Hiển thị</label>
            <select value={pageSize} onChange={e => setPageSize(Number(e.target.value))} className="p-1 border rounded-md">
              <option value={5}>5</option>
              <option value={10}>10</option>
              <option value={20}>20</option>
              <option value={50}>50</option>
            </select>
            <span className="text-sm text-gray-500">{totalResults} kết quả</span>
          </div>
        </div>

        {assignModalOpen && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
            <div className="bg-white rounded-xl shadow-2xl max-w-md w-full">
              <div className="p-6">
                <h2 className="text-2xl font-bold text-gray-800 mb-4">Gán lớp cho {selectedUser?.username}</h2>
                <form onSubmit={handleAssign} className="space-y-4">
                  <div>
                    <label className="block text-sm font-semibold text-gray-700 mb-2">Chọn lớp</label>
                    <select value={selectedClass} onChange={e => setSelectedClass(e.target.value)} className="w-full p-2 border rounded-md">
                      <option value="">-- Chọn lớp --</option>
                      {classes.map(c => (
                        <option key={c._id || c.name} value={c.name}>{c.name}{c.description ? ` - ${c.description}` : ''}</option>
                      ))}
                    </select>
                  </div>
                  <div className="flex justify-end space-x-3 pt-4">
                    <button type="button" onClick={() => setAssignModalOpen(false)} className="px-6 py-2 border border-gray-300 rounded-lg font-semibold text-gray-700 hover:bg-gray-50">Hủy</button>
                    <button type="submit" disabled={assigning} className="px-6 py-2 bg-blue-600 text-white rounded-lg font-semibold">{assigning ? 'Đang gán...' : 'Gán lớp'}</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default AdminUsers;