import { useState, useEffect } from "react";
import api from "../../services/api";
import { useLocation } from "react-router-dom";
import {
  Search,
  Shield,
  User,
  TrendingUp,
  BarChart3,
  Loader,
  UserPlus,
  Users as UsersIcon,
} from "lucide-react";
import { useTheme } from "../../contexts/ThemeContext";

const CreateUserForm = ({ onCreated }) => {
  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [fullName, setFullName] = useState("");
  const [role, setRole] = useState("user");
  const [className, setClassName] = useState("NONE");
  // studentId will be auto-generated by backend for students; do not accept manual input
  const [teacherClasses, setTeacherClasses] = useState("");
  const [loading, setLoading] = useState(false);

  const handleCreate = async (e) => {
    e.preventDefault();
    setLoading(true);
    try {
      const payload = { username, email, password, fullName, role };
      if (role === "user") payload.class = className;
      if (role === "user" && studentId) payload.studentId = studentId;
      if (role === "teacher")
        payload.teacherClasses = teacherClasses
          .split(",")
          .map((s) => s.trim())
          .filter(Boolean);

      await api.post("/users/admin/users", payload);
      setUsername("");
      setEmail("");
      setPassword("");
      setFullName("");
      setRole("user");
      setClassName("NONE");
      setTeacherClasses("");
      setStudentId("");
      if (onCreated) onCreated();
      alert("Tạo người dùng thành công");
    } catch (err) {
      console.error("Create user", err);
      alert(err.response?.data?.error || "Lỗi khi tạo người dùng");
    } finally {
      setLoading(false);
    }
  };

  return (
    <form
      onSubmit={handleCreate}
      className="grid grid-cols-1 md:grid-cols-12 gap-3 items-center"
      autoComplete="off"
    >
      <input
        name="create-username"
        autoComplete="off"
        value={username}
        onChange={(e) => setUsername(e.target.value)}
        placeholder="Tên đăng nhập"
        className="col-span-12 md:col-span-3 p-2 border rounded-md text-sm text-black placeholder-black"
        required
      />
      <input
        name="create-fullname"
        autoComplete="off"
        value={fullName}
        onChange={(e) => setFullName(e.target.value)}
        placeholder="Họ và tên"
        className="col-span-12 md:col-span-3 p-2 border rounded-md text-sm text-black placeholder-black"
      />
      <input
        name="create-email"
        autoComplete="off"
        value={email}
        onChange={(e) => setEmail(e.target.value)}
        placeholder="Email"
        className="col-span-12 md:col-span-3 p-2 border rounded-md text-sm text-black placeholder-black"
        type="email"
        required
      />
      <input
        name="create-password"
        autoComplete="new-password"
        value={password}
        onChange={(e) => setPassword(e.target.value)}
        placeholder="Mật khẩu"
        className="col-span-12 md:col-span-3 p-2 border rounded-md text-sm text-black placeholder-black"
        type="password"
        required
      />

      <label className="sr-only">Role</label>
      <select
        value={role}
        onChange={(e) => setRole(e.target.value)}
        className="col-span-12 md:col-span-2 p-2 border rounded-md text-sm text-black"
      >
        <option value="user">Học sinh</option>
        <option value="teacher">Giáo viên</option>
        <option value="admin">Quản trị</option>
      </select>

      <div className="col-span-12 md:col-span-8">
        {role === "teacher" ? (
          <input
            value={teacherClasses}
            onChange={(e) => setTeacherClasses(e.target.value)}
            placeholder="Các lớp (ví dụ: 10A1,10A2)"
            className="w-full p-2 border rounded-md text-sm text-black placeholder-black"
          />
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
            <input
              value={className}
              onChange={(e) => setClassName(e.target.value)}
              placeholder="Lớp (ví dụ: 10A1)"
              className="w-full p-2 border rounded-md text-sm text-black placeholder-black"
            />
            <input
              value={"(auto)"}
              readOnly
              placeholder="Mã số sinh viên (tự động)"
              className="w-full p-2 border rounded-md text-sm bg-gray-50 text-black placeholder-black"
            />
          </div>
        )}
      </div>

      <div className="col-span-12 md:col-span-2 text-right">
        <button
          type="submit"
          disabled={loading}
          className="inline-flex items-center justify-center w-full bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 rounded-md text-sm"
        >
          {loading ? "Đang tạo..." : "Tạo người dùng"}
        </button>
      </div>
    </form>
  );
};

const AdminUsers = () => {
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [classes, setClasses] = useState([]);
  const [assignModalOpen, setAssignModalOpen] = useState(false);
  const [selectedUser, setSelectedUser] = useState(null);
  const [selectedClass, setSelectedClass] = useState("");
  const [assigning, setAssigning] = useState(false);
  const location = useLocation();
  const params = new URLSearchParams(location.search);
  const initialRole = params.get("role") || "all";
  const [roleFilter, setRoleFilter] = useState(initialRole);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [totalPagesState, setTotalPagesState] = useState(1);
  const [totalResults, setTotalResults] = useState(0);
  const [roleCountsState, setRoleCountsState] = useState({});

  useEffect(() => {
    fetchClasses();
  }, []);

  useEffect(() => {
    fetchUsers();
  }, [roleFilter, page, pageSize, search]);

  const fetchUsers = async () => {
    try {
      setLoading(true);
      const params = {
        page,
        limit: pageSize,
        role: roleFilter,
      };
      if (search) params.search = search;
      const response = await api.get("/users/leaderboard", { params });
      setUsers(response.data.leaderboard || []);
      setTotalPagesState(response.data.totalPages || 1);
      setTotalResults(response.data.total || 0);
      setRoleCountsState(response.data.roleCounts || {});
    } catch (error) {
      console.error("Error fetching users:", error);
    } finally {
      setLoading(false);
    }
  };

  const fetchClasses = async () => {
    try {
      const res = await api.get("/admin/classes");
      setClasses(res.data.classes || []);
    } catch (err) {
      console.error("Error fetching classes", err);
      setClasses([]);
    }
  };

  const roleCounts = roleCountsState;

  const openAssignModal = (user) => {
    setSelectedUser(user);
    setSelectedClass("");
    setAssignModalOpen(true);
  };

  const handleAssign = async (e) => {
    e.preventDefault();
    if (!selectedUser || !selectedClass) return;
    try {
      setAssigning(true);
      await api.post(`/admin/classes/${selectedClass}/students`, {
        userId: selectedUser._id,
      });
      alert("Gán lớp thành công");
      setAssignModalOpen(false);
      fetchUsers();
      fetchClasses();
    } catch (err) {
      console.error("Assign error", err);
      alert(err.response?.data?.error || "Không thể gán lớp");
    } finally {
      setAssigning(false);
    }
  };

  // Resolve a stored user.class (could be name, slug, or compacted) to a known class
  // Returns { name: string, found: boolean }
  const getClassDisplay = (userClass) => {
    if (!userClass) return { name: "---", found: true };
    const raw = String(userClass || "");
    const target = raw.toLowerCase();

    // Handle special reserved class values
    if (target === "admin") return { name: "ADMIN", found: true };
    if (target === "teacher") return { name: "TEACHER", found: true };
    if (target === "none") return { name: "NONE", found: true };

    const found = classes.find((c) => {
      if (!c) return false;
      const name = String(c.name || "").toLowerCase();
      const slug = String(c.slug || c.name || "").toLowerCase();
      const compact = name.replace(/\s+/g, "").toLowerCase();
      return target === name || target === slug || target === compact;
    });
    if (found) return { name: found.name, found: true };
    return { name: String(userClass), found: false };
  };

  // reset page when filter/search/pageSize changes
  useEffect(() => {
    setPage(1);
  }, [roleFilter, search, pageSize]);

  const paginatedUsers = users; // server already returns paginated page
  const totalPages = totalPagesState;

  const { isDark } = useTheme();

  if (loading) {
    return (
      <div
        className={`flex justify-center items-center h-screen ${
          isDark ? "bg-slate-900" : "bg-gray-50"
        }`}
      >
        <div className="flex flex-col items-center gap-4">
          <Loader
            className={`animate-spin ${
              isDark ? "text-cyan-400" : "text-blue-500"
            }`}
            size={40}
          />
          <p className={isDark ? "text-gray-400" : "text-gray-600"}>
            Đang tải dữ liệu...
          </p>
        </div>
      </div>
    );
  }

  return (
    <div
      className={`min-h-screen transition-colors duration-300 ${
        isDark
          ? "bg-gradient-to-br from-slate-900 via-slate-800 to-slate-950"
          : "bg-gradient-to-br from-slate-50 via-white to-slate-100"
      }`}
    >
      <div className="max-w-8xl mx-auto px-4 py-8">
        {/* Header */}
        <div className="mb-8">
          <h1
            className={`text-5xl font-black mb-2 bg-gradient-to-r from-cyan-500 via-blue-500 to-purple-500 bg-clip-text text-transparent`}
          >
            Quản lý Người dùng
          </h1>
          <p
            className={`text-lg font-medium ${
              isDark ? "text-gray-400" : "text-gray-600"
            }`}
          >
            {totalResults} người dùng đã đăng ký trong hệ thống
          </p>
        </div>

        {/* Create user form */}
        <div
          className={`rounded-2xl p-6 mb-6 border ${
            isDark
              ? "bg-gradient-to-br from-slate-800/50 to-slate-700/30 border-slate-700/50"
              : "bg-gradient-to-br from-white to-slate-50 border-gray-200"
          }`}
        >
          <div className="flex items-center gap-3 mb-4">
            <div
              className={`p-3 rounded-xl bg-gradient-to-br from-purple-500 to-pink-500`}
            >
              <UserPlus className="text-white" size={20} />
            </div>
            <h3
              className={`text-lg font-bold ${
                isDark ? "text-white" : "text-gray-900"
              }`}
            >
              Tạo người dùng mới
            </h3>
          </div>
          <CreateUserForm onCreated={fetchUsers} />
        </div>

        {/* Role Filter Buttons */}
        <div className="flex flex-wrap gap-3 mb-6">
          {["admin", "teacher", "user"].map((role) => (
            <button
              key={role}
              onClick={() => setRoleFilter(role)}
              className={`px-4 py-2 rounded-lg font-semibold transition-all ${
                roleFilter === role
                  ? role === "admin"
                    ? "bg-gradient-to-r from-orange-600 to-red-600 text-white shadow-lg"
                    : role === "teacher"
                    ? "bg-gradient-to-r from-purple-600 to-pink-600 text-white shadow-lg"
                    : "bg-gradient-to-r from-blue-600 to-cyan-600 text-white shadow-lg"
                  : isDark
                  ? "bg-slate-800/50 text-gray-300 border border-slate-700/50 hover:bg-slate-700/50"
                  : "bg-white text-gray-700 border border-gray-200 hover:bg-gray-50"
              }`}
            >
              {role === "admin"
                ? "Admin"
                : role === "teacher"
                ? "Giáo viên"
                : "Học sinh"}{" "}
              ({roleCounts[role] || 0})
            </button>
          ))}
        </div>

        {/* Search Bar */}
        <div
          className={`rounded-2xl p-4 mb-6 border ${
            isDark
              ? "bg-gradient-to-br from-slate-800/50 to-slate-700/30 border-slate-700/50"
              : "bg-gradient-to-br from-white to-slate-50 border-gray-200"
          }`}
        >
          <div className="relative">
            <Search
              className={`absolute left-4 top-3.5 ${
                isDark ? "text-gray-500" : "text-gray-400"
              }`}
              size={20}
            />
            <input
              type="text"
              placeholder="Tìm kiếm người dùng..."
              className={`w-full pl-12 pr-4 py-3 rounded-xl transition-all focus:outline-none focus:ring-2 ${
                isDark
                  ? "bg-slate-700/50 border-slate-600/50 text-white placeholder-gray-500 focus:ring-cyan-500"
                  : "bg-white border-gray-200 text-gray-900 placeholder-gray-500 focus:ring-blue-500"
              }`}
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>
        </div>

        {/* Users Table */}
        <div
          className={`rounded-2xl overflow-hidden border ${
            isDark
              ? "bg-gradient-to-br from-slate-800/50 to-slate-700/30 border-slate-700/50"
              : "bg-gradient-to-br from-white to-slate-50 border-gray-200"
          }`}
        >
          <div className="overflow-x-auto">
            <table className="min-w-full">
              <thead>
                <tr
                  className={`border-b ${
                    isDark
                      ? "bg-slate-700/50 border-slate-600/50"
                      : "bg-gray-100/50 border-gray-200"
                  }`}
                >
                  <th
                    className={`px-6 py-4 text-left text-sm font-semibold ${
                      isDark ? "text-gray-300" : "text-gray-700"
                    }`}
                  >
                    Xếp hạng
                  </th>
                  <th
                    className={`px-6 py-4 text-left text-sm font-semibold ${
                      isDark ? "text-gray-300" : "text-gray-700"
                    }`}
                  >
                    Người dùng
                  </th>
                  <th
                    className={`px-6 py-4 text-left text-sm font-semibold ${
                      isDark ? "text-gray-300" : "text-gray-700"
                    }`}
                  >
                    Mã SV
                  </th>
                  <th
                    className={`px-6 py-4 text-left text-sm font-semibold ${
                      isDark ? "text-gray-300" : "text-gray-700"
                    }`}
                  >
                    Lớp
                  </th>
                  <th
                    className={`px-6 py-4 text-left text-sm font-semibold ${
                      isDark ? "text-gray-300" : "text-gray-700"
                    }`}
                  >
                    Email
                  </th>
                  <th
                    className={`px-6 py-4 text-left text-sm font-semibold ${
                      isDark ? "text-gray-300" : "text-gray-700"
                    }`}
                  >
                    Xếp điểm
                  </th>
                  <th
                    className={`px-6 py-4 text-left text-sm font-semibold ${
                      isDark ? "text-gray-300" : "text-gray-700"
                    }`}
                  >
                    Bài giải
                  </th>
                  <th
                    className={`px-6 py-4 text-left text-sm font-semibold ${
                      isDark ? "text-gray-300" : "text-gray-700"
                    }`}
                  >
                    Vai trò
                  </th>
                  <th
                    className={`px-6 py-4 text-left text-sm font-semibold ${
                      isDark ? "text-gray-300" : "text-gray-700"
                    }`}
                  >
                    Hành động
                  </th>
                </tr>
              </thead>
              <tbody
                className={`divide-y ${
                  isDark ? "divide-slate-700/30" : "divide-gray-200"
                }`}
              >
                {paginatedUsers.map((user) => (
                  <tr
                    key={user._id}
                    className={`transition-all ${
                      isDark ? "hover:bg-slate-700/30" : "hover:bg-gray-50"
                    }`}
                  >
                    <td
                      className={`px-6 py-4 font-semibold ${
                        isDark ? "text-gray-300" : "text-gray-600"
                      }`}
                    >
                      #{user.rank}
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex items-center space-x-3">
                        <div className="w-10 h-10 bg-gradient-to-r from-indigo-600 to-purple-600 rounded-full flex items-center justify-center text-white font-bold">
                          {user.username[0].toUpperCase()}
                        </div>
                        <div>
                          <div
                            className={`font-semibold ${
                              isDark ? "text-white" : "text-gray-900"
                            }`}
                          >
                            {user.username}
                          </div>
                          {user.fullName && (
                            <div
                              className={`text-sm ${
                                isDark ? "text-gray-400" : "text-gray-600"
                              }`}
                            >
                              {user.fullName}
                            </div>
                          )}
                        </div>
                      </div>
                    </td>
                    <td
                      className={`px-6 py-4 ${
                        isDark ? "text-gray-400" : "text-gray-600"
                      }`}
                    >
                      {user.studentId || "-"}
                    </td>
                    <td
                      className={`px-6 py-4 ${
                        isDark ? "text-gray-400" : "text-gray-600"
                      }`}
                    >
                      {(() => {
                        const resolved = getClassDisplay(user.class);
                        if (resolved.found) {
                          return resolved.name;
                        }
                        return (
                          <span className="text-sm text-red-500">
                            {resolved.name}
                            <span
                              className={`ml-2 text-xs ${
                                isDark ? "text-gray-500" : "text-gray-600"
                              }`}
                            >
                              (Không tìm thấy)
                            </span>
                          </span>
                        );
                      })()}
                    </td>
                    <td
                      className={`px-6 py-4 ${
                        isDark ? "text-gray-400" : "text-gray-600"
                      }`}
                    >
                      {user.email || "N/A"}
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex items-center space-x-2">
                        <TrendingUp className="text-purple-600" size={16} />
                        <span className="font-semibold text-purple-600">
                          {user.rating}
                        </span>
                      </div>
                    </td>
                    <td
                      className={`px-6 py-4 font-semibold ${
                        isDark ? "text-gray-300" : "text-gray-700"
                      }`}
                    >
                      {user.solvedProblems}
                    </td>
                    <td className="px-6 py-4">
                      <span
                        className={`px-3 py-1 rounded-full text-xs font-semibold inline-flex items-center gap-1 ${
                          user.role === "admin"
                            ? "bg-orange-500/20 text-orange-500 border border-orange-500/30"
                            : user.role === "teacher"
                            ? "bg-purple-500/20 text-purple-500 border border-purple-500/30"
                            : "bg-blue-500/20 text-blue-500 border border-blue-500/30"
                        }`}
                      >
                        {user.role === "admin" ? (
                          <>
                            <Shield size={12} />
                            ADMIN
                          </>
                        ) : user.role === "teacher" ? (
                          <>
                            <BarChart3 size={12} />
                            TEACHER
                          </>
                        ) : (
                          <>
                            <User size={12} />
                            STUDENT
                          </>
                        )}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-right">
                      {user.role === "user" ? (
                        <button
                          onClick={() => openAssignModal(user)}
                          className={`px-3 py-1.5 rounded-lg text-sm font-semibold transition-all ${
                            isDark
                              ? "bg-blue-600/20 text-blue-400 hover:bg-blue-600/40 border border-blue-500/30"
                              : "bg-blue-100 text-blue-700 hover:bg-blue-200 border border-blue-300"
                          }`}
                        >
                          Gán lớp
                        </button>
                      ) : (
                        <span
                          className={`text-sm ${
                            isDark ? "text-gray-500" : "text-gray-500"
                          }`}
                        >
                          -
                        </span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Pagination */}
        <div className="flex items-center justify-between mt-6">
          <div className="flex items-center gap-3">
            <button
              onClick={() => setPage((p) => Math.max(1, p - 1))}
              disabled={page === 1}
              className={`px-4 py-2 rounded-lg font-semibold transition-all ${
                page === 1
                  ? isDark
                    ? "bg-slate-800 text-gray-600 cursor-not-allowed"
                    : "bg-gray-200 text-gray-500 cursor-not-allowed"
                  : isDark
                  ? "bg-slate-700 text-white hover:bg-slate-600"
                  : "bg-white text-gray-900 border border-gray-300 hover:bg-gray-50"
              }`}
            >
              ← Trước
            </button>
            <span
              className={`px-4 py-2 rounded-lg font-semibold ${
                isDark
                  ? "bg-slate-700/50 text-gray-300"
                  : "bg-gray-100 text-gray-700"
              }`}
            >
              Trang {page} / {totalPages}
            </span>
            <button
              onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
              disabled={page === totalPages}
              className={`px-4 py-2 rounded-lg font-semibold transition-all ${
                page === totalPages
                  ? isDark
                    ? "bg-slate-800 text-gray-600 cursor-not-allowed"
                    : "bg-gray-200 text-gray-500 cursor-not-allowed"
                  : isDark
                  ? "bg-slate-700 text-white hover:bg-slate-600"
                  : "bg-white text-gray-900 border border-gray-300 hover:bg-gray-50"
              }`}
            >
              Sau →
            </button>
          </div>

          <div className="flex items-center gap-2">
            <label
              className={`text-sm font-medium ${
                isDark ? "text-gray-300" : "text-gray-700"
              }`}
            >
              Hiển thị
            </label>
            <select
              value={pageSize}
              onChange={(e) => setPageSize(Number(e.target.value))}
              className={`px-3 py-2 rounded-lg font-semibold transition-all ${
                isDark
                  ? "bg-slate-700 text-white border border-slate-600"
                  : "bg-white text-gray-900 border border-gray-300"
              }`}
            >
              <option value={5}>5</option>
              <option value={10}>10</option>
              <option value={20}>20</option>
              <option value={50}>50</option>
            </select>
            <span
              className={`text-sm ${
                isDark ? "text-gray-400" : "text-gray-600"
              }`}
            >
              {totalResults} kết quả
            </span>
          </div>
        </div>

        {assignModalOpen && (
          <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4 z-50">
            <div
              className={`rounded-2xl shadow-2xl max-w-md w-full border ${
                isDark
                  ? "bg-gradient-to-br from-slate-800 to-slate-900 border-slate-700"
                  : "bg-gradient-to-br from-white to-slate-50 border-gray-200"
              }`}
            >
              <div className="p-6">
                <h2
                  className={`text-2xl font-bold mb-4 ${
                    isDark ? "text-white" : "text-gray-900"
                  }`}
                >
                  Gán lớp cho {selectedUser?.username}
                </h2>
                <form onSubmit={handleAssign} className="space-y-4">
                  <div>
                    <label
                      className={`block text-sm font-semibold mb-2 ${
                        isDark ? "text-gray-300" : "text-gray-700"
                      }`}
                    >
                      Chọn lớp
                    </label>
                    <select
                      value={selectedClass}
                      onChange={(e) => setSelectedClass(e.target.value)}
                      className={`w-full px-4 py-3 rounded-lg transition-all focus:outline-none focus:ring-2 ${
                        isDark
                          ? "bg-slate-700/50 border-slate-600/50 text-white focus:ring-blue-500"
                          : "bg-white border-gray-300 text-gray-900 focus:ring-blue-500"
                      } border`}
                    >
                      <option value="">-- Chọn lớp --</option>
                      {classes.map((c) => (
                        <option key={c._id || c.name} value={c.name}>
                          {c.name}
                          {c.description ? ` - ${c.description}` : ""}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div className="flex justify-end gap-3 pt-4">
                    <button
                      type="button"
                      onClick={() => setAssignModalOpen(false)}
                      className={`px-6 py-2 rounded-lg font-semibold transition-all ${
                        isDark
                          ? "border border-slate-600 text-gray-300 hover:bg-slate-700/50"
                          : "border border-gray-300 text-gray-700 hover:bg-gray-50"
                      }`}
                    >
                      Hủy
                    </button>
                    <button
                      type="submit"
                      disabled={assigning}
                      className={`px-6 py-2 rounded-lg font-semibold text-white transition-all ${
                        assigning
                          ? "bg-gray-400 cursor-not-allowed"
                          : "bg-gradient-to-r from-blue-600 to-cyan-600 hover:from-blue-500 hover:to-cyan-500"
                      }`}
                    >
                      {assigning ? "Đang gán..." : "Gán lớp"}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default AdminUsers;
